### ISSUE TITLE
Hobo 1.3: support enum_string I18n

### ISSUE THREAD

**Issue by txapelgorri** [suyccom/hobo-metasearch#6]
When implementing the I18n workaround on enum_string fields described here [1], assumed as official workaround [2], hobo-metasearch stops working. Index page complains with:
```
undefined method `all' for Human::Htype:Class
```
where Human::Htype is the name used in the workaround:
```ruby
# In the model:
class Human < ActiveRecord::Base

hobo_model

Htype = HoboFields::Types::EnumString.for(:real_human,:fake_human)

fields do
  ...
  type   Human::Htype
  ...
  timestamps
end
```

* [1]: https://groups.google.com/forum/#!topic/hobousers/SE3Jex58gOY
* [2]: http://hobocentral.net/manual/i18n#issues-with-enum-string

**Comment by iox** [comment]
Nice work!
